# Generated by Django 3.2.7 on 2021-12-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_account_accountcurrency_accountstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountcurrency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accountcurrency',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountcurrency',
            name='currency',
        ),
        migrations.AlterUniqueTogether(
            name='accountstock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accountstock',
            name='account',
        ),
        migrations.RemoveField(
            model_name='accountstock',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountCurrency',
        ),
        migrations.DeleteModel(
            name='AccountStock',
        ),
    ]
